import XCTest
@testable import JarvisKit

// The vectors below were generated by the Mac daemon's own directCrypto.js.
// They pin this port to the wire, byte for byte: HKDF derivation, raw
// DEFLATE, AES-256-GCM with the sender name (and, for binary, the
// timestamp) as AAD. A byte of drift fails here, not in the field.
final class DirectCryptoTests: XCTestCase {

    let secret = String(repeating: "a", count: 64)
    let vectorTs: Int64 = 1_755_700_000_000
    let vectorNonce = Data([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])

    func testRemoteKeyMatchesNode() throws {
        let key = try DirectCrypto.remoteKeyFor(secretHex: secret)
        XCTAssertEqual(
            key.hexString,
            "ea0caf873be8104371102f25ab03bca882b65273db18dfe99919602926382103")
    }

    func testOpensNodeMintedTextEnvelope() throws {
        let key = try DirectCrypto.remoteKeyFor(secretHex: secret)
        let envelope = #"{"v":1,"from":"mac","ts":1755700000000,"# +
            #""n":"AAECAwQFBgcICQoL","# +
            #""c":"FGd7jRjWDxBVrxrjRoVRn0YSKcS8kHRfDBl2Q3sZ7KOfrV9wjYzv9w=="}"#
        let opened = DirectCrypto.open(key: key, selfName: "phone", raw: envelope,
                                       seen: ReplayGuard(), now: vectorTs)
        XCTAssertEqual(opened?["type"] as? String, "probe")
        XCTAssertEqual((opened?["n"] as? NSNumber)?.intValue, 7)
    }

    func testOpensNodeMintedBinaryEnvelope() throws {
        let key = try DirectCrypto.remoteKeyFor(secretHex: secret)
        let envelope = Data(base64Encoded:
            "AQABAgMEBQYHCAkKCwAAAZjH3/UAzFQwSFH6esZo6kDlDhKYtQqZeQW9/zF03opd")!
        let clear = DirectCrypto.openBinary(key: key, from: "mac", buf: envelope,
                                            now: vectorTs)
        XCTAssertEqual(clear.flatMap { String(data: $0, encoding: .utf8) }, "sealed door")
    }

    func testTextRoundTrip() throws {
        let key = try DirectCrypto.remoteKeyFor(secretHex: secret)
        let sealed = DirectCrypto.seal(key: key, from: "phone",
                                       payload: ["type": "intent", "text": "hello"])!
        let opened = DirectCrypto.open(key: key, selfName: "mac", raw: sealed,
                                       seen: ReplayGuard())
        XCTAssertEqual(opened?["text"] as? String, "hello")
    }

    func testOwnEnvelopeRefused() throws {
        let key = try DirectCrypto.remoteKeyFor(secretHex: secret)
        let sealed = DirectCrypto.seal(key: key, from: "phone", payload: ["a": 1])!
        XCTAssertNil(DirectCrypto.open(key: key, selfName: "phone", raw: sealed,
                                       seen: ReplayGuard()))
    }

    func testStaleTimestampRefused() throws {
        let key = try DirectCrypto.remoteKeyFor(secretHex: secret)
        let sealed = DirectCrypto.seal(key: key, from: "mac", payload: ["a": 1],
                                       ts: vectorTs)!
        XCTAssertNil(DirectCrypto.open(key: key, selfName: "phone", raw: sealed,
                                       seen: ReplayGuard(),
                                       now: vectorTs + DirectCrypto.windowMs + 1))
    }

    func testTextNonceReplayRefused() throws {
        let key = try DirectCrypto.remoteKeyFor(secretHex: secret)
        let guardMap = ReplayGuard()
        let sealed = DirectCrypto.seal(key: key, from: "mac", payload: ["a": 1])!
        XCTAssertNotNil(DirectCrypto.open(key: key, selfName: "phone", raw: sealed,
                                          seen: guardMap))
        XCTAssertNil(DirectCrypto.open(key: key, selfName: "phone", raw: sealed,
                                       seen: guardMap))
    }

    func testBinaryRoundTripAndReplay() throws {
        let key = try DirectCrypto.remoteKeyFor(secretHex: secret)
        let guardMap = ReplayGuard()
        let sealed = DirectCrypto.sealBinary(key: key, from: "mac",
                                             data: Data("voice".utf8))!
        XCTAssertEqual(DirectCrypto.openBinary(key: key, from: "mac", buf: sealed,
                                               seen: guardMap),
                       Data("voice".utf8))
        XCTAssertNil(DirectCrypto.openBinary(key: key, from: "mac", buf: sealed,
                                             seen: guardMap))
    }

    func testWrongSenderAadRefused() throws {
        let key = try DirectCrypto.remoteKeyFor(secretHex: secret)
        let sealed = DirectCrypto.sealBinary(key: key, from: "mac",
                                             data: Data("x".utf8))!
        XCTAssertNil(DirectCrypto.openBinary(key: key, from: "phone", buf: sealed))
    }

    func testMalformedSecretThrows() {
        XCTAssertThrowsError(try DirectCrypto.remoteKeyFor(secretHex: "zz"))
        XCTAssertThrowsError(try DirectCrypto.remoteKeyFor(secretHex: "abc"))
    }
}
